sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: tyz1597856
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRiw8kG1mkYsiDUF1xR
    access-key-secret: EYrZzQzNVgSQAYwN98NqWDZmZgytmZ
    bucket-name: sky-tyz
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1

